<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>WpfAppGui</RootNamespace>
    <AssemblyName>WpfAppGui</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <None Update="Config.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
